### ISSUE TITLE
Create MVP of map-based quiz game

### ISSUE THREAD

**Issue by christophernixon** [christophernixon/DevOps-Pipeline-sweng#52]
## Description
We would like a minimum viable product of a map-based quiz game. The user should be able to start a game, answer a quiz question by dropping a marker on the map, and receive feedback on how close they were to the target.

## Tasks
These will be fairly high-level descriptions of the tasks we will need to complete this, these tasks should each be taken as an issue, and broken down further if necessary. 
- [x] Implement a map
- [x] Present user with a 'Start Game' button
- [x] Implement draggable markers on the map
- [x] Upon pressing on the 'Start Game' button, present user with a quiz question, and a 'Answer Question' button.
- [x] Upon the user dragging the marker to where they think the answer is, and pressing the 'Answer Question' button, calculate the distance between the location of the user's marker and the actual location
- [x] Present user with a popup which will give the distance from the location their marker was, and a 'Next question' button.
